### ISSUE TITLE
Switch to `go-katapult@next` in new Provider Framework implementation

### ISSUE THREAD

**Issue by jimeh** [krystal/terraform-provider-katapult#121]
When https://github.com/krystal/go-katapult/issues/150 is completed, there will be a new "next" version of the `go-katapult` client, that is generated from Katapult's OpenAPI schema.

We should try switching the new `interval/v6provider` package over to this new client. This will be the first real-world use of the new client, serving as a good way to evaluate it, and make adjustments to it if needed. While also slowly moving the Terraform provider codebase forward as well.

**Comment by ikadix** [comment]
Yup happy for this to be closed
