### ISSUE TITLE
List of data centre permalinks?

### ISSUE THREAD

**Issue by LondonAppDev** [krystal/terraform-provider-katapult#81]
I'm trying to use the Katapult Terraform provider, but I cannot figure out what value to put for `KATAPULT_DATA_CENTER`... I tried `LON-1` but it says it's incorrect. I looked everywhere in the docs but can't find a list.

**Comment by jimeh** [comment]
Apologies for the confusion. The provider and its docs are still very much a work in progress.

The current list of data centers can be fetched via Katapult's [Public API](https://apidocs.k.io/katapult-public/routes/data_centers/get/) (no auth) and the [Core API](https://apidocs.k.io/katapult/routes/data_centers/get/) (requires auth).

The public API endpoint is: [`https://api.katapult.io/public/v1/data_centers`](https://api.katapult.io/public/v1/data_centers), which as of writing returns:

```json
{
	"data_centers": [
		{
			"id": "dc_Wm37yAq0BHhKXsPa",
			"name": "Amsterdam",
			"permalink": "nl-ams-01",
			"country": "NL"
		},
		{
			"id": "loc_UUhPmoCbpic6UX0Y",
			"name": "London",
			"permalink": "uk-lon-01",
			"country": "GB"
		},
		{
			"id": "dc_TfDSMyVYoS3fJnSt",
			"name": "New York",
			"permalink": "us-nyc-01",
			"country": "US"
		},
		{
			"id": "dc_U3UVcwL8GKXJdsgw",
			"name": "Phoenix",
			"permalink": "us-azp-01",
			"country": "US"
		}
	]
}
```

I've also raised #82, which will enable you fetch a list of data centers via the Terraform provider once implemented.

**Comment by LondonAppDev** [comment]
Thank you!
